# Generated by Django 5.0.6 on 2024-07-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, verbose_name='عنوان')),
                ('how', models.CharField(help_text='این فیلد اسم شما را نشان میدهد', max_length=63, verbose_name='اسم')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('body', models.TextField(verbose_name='متن')),
                ('slug', models.SlugField(blank=True, default='', null=True, unique=True)),
                ('count', models.PositiveSmallIntegerField(default=1, help_text='این فیلد مشخص میکند این یاداشت چند بار نمایش داده شود.برای این فیلد باید عددی بالای صفر انتخاب کنید.', verbose_name='تعداد')),
            ],
        ),
    ]
