# Generated by Django 5.0.6 on 2024-07-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onenote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='how',
            new_name='who',
        ),
    ]
